### ISSUE TITLE
oParameters.js bug

### ISSUE THREAD

**Issue by iamgxh** [zouwei/onela#3]
getDeleteParameters

默认operator 没有加，导致where条件为空，整张表清空。。

if (!paras.keyword[i].hasOwnProperty('operator')) {
                paras.keyword[i].operator = "=";
            }

**Comment by iamgxh** [comment]
v1.1.9 可能是版本太久了，不知新版本是否修复了

**Comment by zouwei** [comment]
@iamgxh 请在业务代码编写时注意删除条件，此bug暂时还存在，会在下一个版本进行修复，感谢提供意见反馈。

**Comment by iamgxh** [comment]
暂时在源码里修改了 @zouwei

**Comment by zouwei** [comment]
@iamgxh 方便提供bug修复源码吗？我可以直接使用bug修复的代码进行版本发布，并署上你的名字，我偷个懒~哈哈

**Comment by iamgxh** [comment]
在getDeleteParameters.js 加上
if (!paras.keyword[i].hasOwnProperty('operator')) {
                paras.keyword[i].operator = "=";
            }
就是一个if判断，你应该检查下所有的方法里有没有漏掉这个判断，哈哈哈，这个懒你偷不了
@zouwei

**Comment by zouwei** [comment]
@iamgxh 感谢感谢！
